package com.cursor.greendict;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table WORD.
*/
public class wordDao extends AbstractDao<word, Long> {

    public static final String TABLENAME = "WORD";

    /**
     * Properties of entity word.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Raw_word = new Property(1, String.class, "raw_word", false, "RAW_WORD");
        public final static Property Interpretation = new Property(2, String.class, "interpretation", false, "INTERPRETATION");
        public final static Property Sequence = new Property(3, int.class, "sequence", false, "SEQUENCE");
        public final static Property DictId = new Property(4, long.class, "dictId", false, "DICT_ID");
    };

    private DaoSession daoSession;

    private Query<word> dict_WordsQuery;

    public wordDao(DaoConfig config) {
        super(config);
    }
    
    public wordDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'WORD' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'RAW_WORD' TEXT NOT NULL ," + // 1: raw_word
                "'INTERPRETATION' TEXT," + // 2: interpretation
                "'SEQUENCE' INTEGER NOT NULL ," + // 3: sequence
                "'DICT_ID' INTEGER NOT NULL );"); // 4: dictId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'WORD'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, word entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getRaw_word());
 
        String interpretation = entity.getInterpretation();
        if (interpretation != null) {
            stmt.bindString(3, interpretation);
        }
        stmt.bindLong(4, entity.getSequence());
        stmt.bindLong(5, entity.getDictId());
    }

    @Override
    protected void attachEntity(word entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public word readEntity(Cursor cursor, int offset) {
        word entity = new word( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // raw_word
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // interpretation
            cursor.getInt(offset + 3), // sequence
            cursor.getLong(offset + 4) // dictId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, word entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setRaw_word(cursor.getString(offset + 1));
        entity.setInterpretation(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setSequence(cursor.getInt(offset + 3));
        entity.setDictId(cursor.getLong(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(word entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(word entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "words" to-many relationship of dict. */
    public List<word> _queryDict_Words(long dictId) {
        synchronized (this) {
            if (dict_WordsQuery == null) {
                QueryBuilder<word> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.DictId.eq(null));
                queryBuilder.orderRaw("SEQUENCE ASC");
                dict_WordsQuery = queryBuilder.build();
            }
        }
        Query<word> query = dict_WordsQuery.forCurrentThread();
        query.setParameter(0, dictId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getdictDao().getAllColumns());
            builder.append(" FROM WORD T");
            builder.append(" LEFT JOIN DICT T0 ON T.'DICT_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected word loadCurrentDeep(Cursor cursor, boolean lock) {
        word entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        dict dict = loadCurrentOther(daoSession.getdictDao(), cursor, offset);
         if(dict != null) {
            entity.setDict(dict);
        }

        return entity;    
    }

    public word loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<word> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<word> list = new ArrayList<word>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<word> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<word> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
